apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: licenses-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: n3uron
spec:
  type: NodePort
  selector:
    app: n3uron
  ports:
    - port: 8003
      protocol: TCP
      targetPort: 8003

---
apiVersion: v1
kind: Pod
metadata:
  name: n3uron
spec:
  containers:
    - name: n3uron
      image: n3uronhub/n3uron:v1.21.6
      env:
        - name: HOSTNAME
          value: n3uron-k8s-01
      volumeMounts:
        - name: config
          mountPath: /opt/n3uron/config
          subPath: config
        - name: data
          mountPath: /opt/n3uron/data
        - name: log
          mountPath: /opt/n3uron/log
        - name: licenses
          mountPath: /opt/n3uron/licenses
      securityContext:
        capabilities:
          add: ["CAP_SYS_ADMIN"]
      ports:
        - containerPort: 8003
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: config-pvc
    - name: data
      persistentVolumeClaim:
        claimName: data-pvc
    - name: log
      persistentVolumeClaim:
        claimName: log-pvc
    - name: licenses
      persistentVolumeClaim:
        claimName: licenses-pvc
